mosquitto-home-assistant initial check in

diff --git a/rootfs/etc/cont-init.d/98-mosquitto b/rootfs/etc/cont-init.d/98-mosquitto
--- a/rootfs/etc/cont-init.d/98-mosquitto
+++ b/rootfs/etc/cont-init.d/98-mosquitto
@@ -4,36 +4,97 @@ MARKER_FILE=/.98-mosquitto
 MOSQUITTO_AUTH_VERSION=0.1.4
 
 if [ -f "${MARKER_FILE}" ]; then
-    echo "mosquitto already installed"
+    echo "mosquitto broker already configured"
     exit 0
 fi
 
-apk add --no-cache \
-    curl \
-    mosquitto \
-    musl \
-    openssl \
-    pwgen \
-    socat
+set +u
 
-apk add --no-cache --virtual .build-dependencies \
-    build-base \
-    curl-dev \
-    git \
-    mosquitto-dev \
-    openssl-dev
+SYSTEM_USER=/mosquitto/data/system_user.json
 
-cd /usr/src
-git clone --depth 1 -b "${MOSQUITTO_AUTH_VERSION}" https://github.com/pvizeli/mosquitto-auth-plug
-cd mosquitto-auth-plug
-cp config.mk.in config.mk
-make
-mkdir -p /usr/share/mosquitto
-cp -f auth-plug.so /usr/share/mosquitto
+function write_system_users() {
+    (
+        echo "{\"homeassistant\": {\"password\": \"$HOMEASSISTANT_PW\"}, \"addons\": {\"password\": \"$ADDONS_PW\"}}"
+    ) > "${SYSTEM_USER}"
+}
 
-apk del .build-dependencies
-rm -fr /usr/src/mosquitto-auth-plug
+function call_homeassistant() {
+    local method=$1
+    local path=$2
+    local data="${3}"
+    local token=
 
-cp -f /etc/mosquitto.conf /config
+    token="Authorization: Bearer ${HOMEASSISTANT_TOKEN}"
+    url="${HOMEASSISTANT_URL}/${path}"
+
+    # Call API
+    if [ -n "${data}" ]; then
+        curl -f -s -X "${method}" -d "${data}" -H "${token}" "${url}"
+    else
+        curl -f -s -X "${method}" -H "${token}" "${url}"
+    fi
+
+    return $?
+}
+
+function constrain_host_config() {
+    local user=$1
+    local password=$2
+
+    echo "{"
+    echo "  \"host\": \"$(hostname)\","
+    echo "  \"port\": 1883,"
+    echo "  \"ssl\": false,"
+    echo "  \"protocol\": \"3.1.1\","
+    echo "  \"username\": \"${user}\","
+    echo "  \"password\": \"${password}\""
+    echo "}"
+}
+
+function constrain_discovery() {
+    local user=$1
+    local password=$2
+    local config=
+
+    config="$(constrain_host_config "${user}" "${password}")"
+    echo "{"
+    echo "  \"service\": \"mqtt\","
+    echo "  \"config\": ${config}"
+    echo "}"
+}
+
+## Main ##
+
+echo "Setup mosquitto configuration"
+
+# Prepare System Accounts
+if [ ! -e "${SYSTEM_USER}" ]; then
+    HOMEASSISTANT_PW="$(pwgen 64 1)"
+    ADDONS_PW="$(pwgen 64 1)"
+
+    bashio::log.info "Initialize system configuration."
+    write_system_users
+else
+    HOMEASSISTANT_PW=$(jq --raw-output '.homeassistant.password' $SYSTEM_USER)
+    ADDONS_PW=$(jq --raw-output '.addons.password' $SYSTEM_USER)
+fi
+
+# Initialize Service
+if call_homeassistant GET "services/mqtt" | jq --raw-output ".data.host" | grep -v "$(hostname)" > /dev/null; then
+    echo "There is already an MQTT service running!"
+else
+    echo "Initialize Home Assistant Add-on services"
+    if ! call_homeassistant POST "services/mqtt" "$(constrain_host_config addons "${ADDONS_PW}")" > /dev/null; then
+        echo "Can't setup Home Assistant service mqtt"
+    fi
+
+    echo "Initialize Home Assistant discovery"
+    if ! call_homeassistant POST "discovery" "$(constrain_discovery homeassistant "${HOMEASSISTANT_PW}")" > /dev/null; then
+        echo "Can't setup Home Assistant discovery mqtt"
+    fi
+fi
+
+cp /etc/mosquitto/auth_srv.sh /bin/auth_srv.sh
+chmod +x /bin/auth_srv.sh
 
 touch ${MARKER_FILE}
